/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function BeagleModel(props) {
  const { nodes, materials } = useGLTF("/Beagle.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Geo_Beagle.geometry}
        material={materials.lambert2SG}
      />
    </group>
  );
}

useGLTF.preload("/Beagle.glb");