/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function LaptopModel(props) {
  const { nodes, materials } = useGLTF("/Laptop.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Laptop_01_Cube025-Mesh"].geometry}
        material={materials["1A1A1A"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Laptop_01_Cube025-Mesh_1"].geometry}
        material={materials["039BE5"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Laptop_01_Cube025-Mesh_2"].geometry}
        material={materials.F44336}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Laptop_01_Cube025-Mesh_3"].geometry}
        material={materials.FF9800}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Laptop_01_Cube025-Mesh_4"].geometry}
        material={materials["455A64"]}
      />
    </group>
  );
}

useGLTF.preload("/Laptop.glb");